### ISSUE TITLE
identity column

### ISSUE THREAD

**Issue by romanstr** [LycanII/LzScripts#8]
add possibility to export identity column

**Comment by LycanII** [comment]
Hi @romanstr, 
Many thanks for the feedback,
yes, I think it's a good idea, I will analyse it and get back to you on this.

**Comment by LycanII** [comment]
Hi @romanstr ,
For this, I have added new Settings to Enable or Disable this behavior, 
Kindly get the latest version to confirm.  [See This](https://github.com/LycanII/LzScripts/releases/tag/v.1.2.0)

**Comment by LycanII** [comment]
I will now close this issue.
