### ISSUE TITLE
Support strings with single quotes

### ISSUE THREAD

**Issue by ErikPilsits-RJW** [LycanII/LzScripts#9]
Strings with embedded single quotes need to be escaped in the insert scripts for valid syntax.

**Comment by LycanII** [comment]
hello thanks for the prompt, 
yes single quotes need to be escaped, the fix should be available in the next release

**Comment by LycanII** [comment]
Hi @ErikPilsits-RJW , 
This has now been fixed, kindly get the latest version to confirm
